/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  images: { formats: ["image/avif", "image/webp"] },
  async redirects() {
    return [
      { source: "/home-visit-physiotherapy", destination: "/home-visit-physiotherapy-newcastle", permanent: true },
      { source: "/ndis-physiotherapy", destination: "/ndis-physiotherapy-newcastle", permanent: true },
      { source: "/support-at-home-physiotherapy", destination: "/support-at-home-physiotherapy-newcastle", permanent: true },
      { source: "/falls-prevention", destination: "/falls-prevention-physiotherapy-newcastle", permanent: true },
      { source: "/referrals", destination: "/refer-a-patient", permanent: true },
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/ndis-&-support-at-home", destination: "/ndis-physiotherapy-newcastle", permanent: true },
      { source: "/faq", destination: "/faqs", permanent: true },
      { source: "/bulk-bill-1", destination: "/contact", permanent: true },
      { source: "/physiotherapy-auburn", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-ryde", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-parramatta", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-granville", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-ermington", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-carlingford", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-epping", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-eastwood", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-gladesville", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-hunters-hill", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-wentworth-point", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-drummoyne", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-five-dock", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-burwood", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-ashfield", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-newington", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-silverwater", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-meadowbank", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-homebush-west", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-north-strathfield", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-strathfield-south", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-concord-west", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-cabarita", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-mortlake", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-breakfast-point", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-croydon", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-berala", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-regents-park", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-rosehill", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-harris-park", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-rydalmere", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-melrose-park", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-dundas", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-west-ryde", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-putney", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-denistone", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/physiotherapy-north-ryde", destination: "/physiotherapy-sydney", permanent: true },
      { source: "/blog/how-to-get-up-safely-after-a-fall", destination: "/blog/getting-up-safely-after-a-fall", permanent: true },
    ];
  },
};

export default nextConfig;
